// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clients": {
            "post": {
                "description": "Registra um novo cliente com nome e e-mail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Registra um novo cliente",
                "parameters": [
                    {
                        "description": "Registrar novo cliente request",
                        "name": "createClientRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.createClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente registrado",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{cpf}": {
            "get": {
                "description": "buscar um cliente pelo Cpf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Busca um cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cliente",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cliente nao encontrado",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "Lista os pedidos ordenados pelor seu status na seguinte ordem Pronto \u003e Em preparação \u003e Recebido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Lista os pedidos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limite de pedidos",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pedidos listados",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ListOrdersResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo pedido com o pagamento pendente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Criar um novo pedido (checkout)",
                "parameters": [
                    {
                        "description": "Criar ordem body",
                        "name": "createOrderRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.createOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ordem criada",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/{id}/payment-status": {
            "get": {
                "description": "Consultar o status de pagamento de um pedido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Consultar status de pagamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status do pagamento",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.OrderPaymentStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pedido não encontrado",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/{id}/status": {
            "patch": {
                "description": "Atualizar status do pedido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Atualizar status do pedido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "preparing",
                            "ready",
                            "completed"
                        ],
                        "type": "string",
                        "description": "Status do pedido",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status do pagamento",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.UpdateOrderStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pedido não encontrado",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Lista os produtos podendo buscar por categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Lista os produtos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da categoria",
                        "name": "category_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produtos listados",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ProductResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "registra um novo produto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Registra um novo produto",
                "parameters": [
                    {
                        "description": "Registrar novo produto body",
                        "name": "createProductRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.createProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produto registrado",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "put": {
                "description": "Atualiza um produto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Atualiza um produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Atualizar produto body",
                        "name": "updateProductRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.updateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produto atualizado",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Produto nao encontrado",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um produto por meio de seu identificador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Remove um produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produto removido",
                        "schema": {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Produto nao encontrado",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_delivery_http_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Error message 1",
                        " Error message 2"
                    ]
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_delivery_http_handler.createClientRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john-doe@email.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "internal_delivery_http_handler.createOrderRequest": {
            "type": "object",
            "required": [
                "products"
            ],
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_delivery_http_handler.orderProductRequest"
                    }
                }
            }
        },
        "internal_delivery_http_handler.createProductRequest": {
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "category_id": {
                    "type": "string",
                    "minLength": 1,
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "description": {
                    "type": "string",
                    "example": "Lanche com batata"
                },
                "image": {
                    "type": "string",
                    "example": "https://"
                },
                "name": {
                    "type": "string",
                    "example": "Lanche"
                },
                "value": {
                    "type": "number",
                    "example": 10.9
                }
            }
        },
        "internal_delivery_http_handler.orderProductRequest": {
            "type": "object",
            "required": [
                "product_id",
                "quantity"
            ],
            "properties": {
                "observation": {
                    "type": "string",
                    "example": "Lanche com batata"
                },
                "product_id": {
                    "type": "string",
                    "minLength": 1,
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "quantity": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_delivery_http_handler.updateProductRequest": {
            "type": "object",
            "required": [
                "name",
                "value"
            ],
            "properties": {
                "category_id": {
                    "type": "string",
                    "minLength": 1,
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "description": {
                    "type": "string",
                    "example": "Lanche com batata"
                },
                "image": {
                    "type": "string",
                    "example": "https://"
                },
                "name": {
                    "type": "string",
                    "example": "Lanche"
                },
                "value": {
                    "type": "number",
                    "example": 10.9
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.CategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "name": {
                    "type": "string",
                    "example": "Lanche"
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.ClientResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john-doe@email.com"
                },
                "id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.ListOrdersResponse": {
            "type": "object",
            "properties": {
                "completed_orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.OrderResponse"
                    }
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.OrderPaymentStatusResponse": {
            "type": "object",
            "properties": {
                "paymentStatus": {
                    "type": "string",
                    "example": "payment_approved"
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.OrderResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "created_at": {
                    "type": "string",
                    "example": "1970-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "number": {
                    "type": "integer",
                    "example": 123
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_entities.OrderStatus"
                        }
                    ],
                    "example": "received"
                },
                "total": {
                    "type": "number",
                    "example": 100.9
                },
                "updated_at": {
                    "type": "string",
                    "example": "1970-01-01T00:00:00Z"
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.ProductResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/post-tech-challenge-10soat_internal_delivery_http_mapper.CategoryResponse"
                },
                "created_at": {
                    "type": "string",
                    "example": "1970-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Lanche com bacon"
                },
                "id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "image": {
                    "type": "string",
                    "example": "https://"
                },
                "name": {
                    "type": "string",
                    "example": "Lanche 1"
                },
                "updated_at": {
                    "type": "string",
                    "example": "1970-01-01T00:00:00Z"
                },
                "value": {
                    "type": "number",
                    "example": 10.9
                }
            }
        },
        "post-tech-challenge-10soat_internal_delivery_http_mapper.UpdateOrderStatusResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "1970-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "ed6ac028-8016-4cbd-aeee-c3a155cdb2a4"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/post-tech-challenge-10soat_internal_entities.OrderStatus"
                        }
                    ],
                    "example": "received"
                },
                "updated_at": {
                    "type": "string",
                    "example": "1970-01-01T00:00:00Z"
                }
            }
        },
        "post-tech-challenge-10soat_internal_entities.OrderStatus": {
            "type": "string",
            "enum": [
                "payment_pending",
                "received",
                "preparing",
                "ready",
                "completed"
            ],
            "x-enum-varnames": [
                "OrderStatusPaymentPending",
                "OrderStatusReceived",
                "OrderStatusPreparing",
                "OrderStatusReady",
                "OrderStatusCompleted"
            ]
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "POS-Tech API",
	Description:      "API em Go para o desafio na pos-tech fiap de Software Architecture.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
